# 2025.6.29 - 基本文法 8-3 エラーハンドリング（例外処理）

## 目的

PHPで安全なプログラムを書くために、`try-catch構文` を使った `エラーハンドリング` の基礎を理解する

## 目次

- [`エラーハンドリング` とは](#1)
- [try-catch構文](#2)
- [Exceptionクラス](#3)

## MEMO

<a id="1"></a>

### `エラーハンドリング` とは

- プログラムが予期しない状況（例外）に遭遇した際に、その状況に対処するための仕組み  
    例）  
ファイルが見つからない、数値ではない値を計算しようとした …etc  
- エラーハンドリングをしない場合、エラーが発生するとプログラムが即座に停止し、エラーメッセージが表示されるだけで、ユーザーは何もできない状況になる  

#### エラーハンドリングのポイント

- エラーの種類を把握する  
→ どのようなエラーが発生する可能性があるかを把握し、適切なエラーハンドリングを行うことが重要
- エラー処理を分散させない  
→ 同じエラーに対する処理は、できるだけ一箇所にまとめることで、コードの可読性と保守性を高めることができる
- エラー処理を過剰にしない  
→ 必要な箇所にのみエラーハンドリングを実装し、コードの冗長化を防ぐことが重要

[参考: 「分かりそう」で「分からない」でも「分かった」気になれるIT用語辞典 : エラーハンドリング](https://wa3.i-3-i.info/word1424.html?piyotype=etc)

#### 例外処理の流れ

1. 例外を発生させる(例外を投げる)  

    `throw` を使用することで、例外を発生させることができる。

    ```php
    throw new Exception('エラーメッセージ');
    ```
    → `throw` するだけでは、例外処理をすることはできない  
    例外処理をする為には、`throw` で投げられた例外を受け取り、処理するプログラムを作成する必要がある  


2. 例外を捕捉する  

    `throw` で投げられた例外を捕捉し、処理するには、`try～catch～fainally`を使用する。

    [参考: Qiita PHP 例外処理](https://qiita.com/shihoin2/items/f5608f7316232cffec2d)  

#### `throw` とは  

「自分でエラーを発生させるためのスイッチ」みたいなもの  

`throw` の役割は  
→ 「このまま処理を続けたらマズい！」というときに、自分からエラーを“投げる”ことで、処理の流れを中断してキャッチ側へ渡す  

何のために使うのか  
- 「この条件は許しちゃダメ！」という場面で処理を止めたい
- コードの中で明確に「これはエラーです」と判断を加えたい
- ユーザーにわかりやすいエラー説明を表示するための仕組みに使える

覚え方のコツ  
- `throw` = 問題発生の“投げるボール”
- `catch` = そのボールを“受け取るグローブ”
投げられたエラーを、どこかでキャッチ（受け止め）ないと、プログラムが止まってしまうので注意！

---
<a id="2"></a>

### try～catch～fainally構文

- `try` : 実行したい処理を記述
- `catch` : エラーが起きた時の処理を記述
- `fibally` : 例外の有無に関わらず最後に常に実行される処理を記述
- `例外（Exception）` を使うことでエラーをキャッチして処理できる  

```php
try {
    // 例外が発生する可能性があるコード
} catch (Exception $e) {
    // 例外が発生したときに実行されるコード
} finally {
    // 例外の有無に関わらず最後に実行されるコード
}
```
※try-catch構文における `$e` は、例外が発生した際に、その例外オブジェクトを保持するための変数名  
>`$e` は catch ブロック内で有効な変数で、try ブロックで発生した例外オブジェクトを参照します。このオブジェクトには、エラーの種類を示す type やエラーメッセージを示す message など、例外に関する情報が含まれています。
>

[参考: PHPにおけるtry-catch文（例外処理）の使い方を解説します](https://techplay.jp/column/1824)  
[参考: PHP Try Catchの基本](https://hypertextpreprocessor.com/php-try-catch%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB-%E5%9F%BA%E7%A4%8E%E3%81%8B%E3%82%89%E5%BF%9C%E7%94%A8%E3%81%BE%E3%81%A7/277/)   

```php
try {
    // 例外が発生する可能性のある処理
    $num = 10;
    $div = 0;
    if ($div === 0) {
        throw new Exception("0で割ることはできません。");
    }
    $result = $num / $div;
    echo $result;
} catch (Exception $e) {
    // エラー発生時の処理
    echo "エラー発生: " . $e->getMessage();
}
```
---
<a id="3"></a>

### Exceptionクラス

- `$e->getMessage()` : エラーメッセージを取得
- `$e->getCode()` や `$e->getLine()` などで詳細情報も取得できる

[参考: PHPマニュアル : 例外(exceptions)](https://www.php.net/manual/ja/language.exceptions.php)  

---

## セキュリティ面での注意

- 入力値は常にバリデーションする
- エラーメッセージは `内部の情報を出しすぎない` ようにする（開発中以外は詳細表示を避ける）

---

### 練習問題 

ユーザーが入力した数値で割り算をするフォームを作成し、0で割ろうとした場合はエラーをキャッチして表示するプログラムの作成

---
## 作業チェックリスト

- try-catch構文の書き方が理解できたか
- Exception の使い方を覚えたか
- エラー時に止まらずに処理できたか

---
## 疑問・課題

- HTMLの `placeholder属性` は、入力フィールドに表示されるヒントテキストを指定できる
- 例外処理をする上で大切なこと → `例外を握りつぶさない`  
→ 例外を握りつぶすとは、例外をcatchした後、処理を書かないこと
- スローしてる時、else の出力がされない  
→ あらゆる場合において `throw` された瞬間に `try` ブロックの処理が中断され、`catch` にジャンプする  

    throw されたときの流れ  
    - `try` ブロック内で `throw new Exception(...)` されたら  
    → その瞬間に残りの `try` 内の処理は スキップ される
    - `catch` ブロックにジャンプして、例外オブジェクトを受け取って処理する
    - `else` や `finally` は構造上の位置によって処理されるかどうかが変わる

- 数値のバリデーションも記述したら、elseの中の処理が実行されるようになった  

    - `is_numeric()` を使う前 → 文字列や空でも通過して `throw` が走る可能性がある
    - `is_numeric()` を入れた後 → 数値じゃないものは `if` で弾かれるようになり、`else` のメッセージが出るようになる

---

参考: []()
